# Experiment configuration files

# experiment name (determines output folder)
exp_name: unrolling_GNN_WDN
# data folder
data_folder: ../data_generation/datasets

# seeds for reproducibility
seeds:
    np: 4320
    torch: 3407

# networks to use
networks: ['FOS_100']
#networks: ['FOS','MOD','PES','BAK','RuralNetwork' ]

# number of training samples to use (if < than total)
tra_num: 8000


# model architectures to train
algorithms:
    - NeumannEPANET
# # hyper params for each model
hyperParams:
    NeumannEPANET:
        K:
            - 1
#            - 10
#            - 100
#            - 250
adamParams:
    lr: 0.001
    weight_decay: 0


trainParams:
    num_epochs: 40
    batch_size: 256

lossParams:
        alpha: 0