# Experiment configuration files

# experiment name (determines output folder)
exp_name: unrolling_WDN
# data folder
data_folder: ./data

# seeds for reproducibility
seeds:
    np: 4320
    torch: 3407

# networks to use
networks: ['FOS', 'MOD', 'PES', 'BAK', 'RuralNetwork']

# number of training samples to use (if < than total)
tra_num: 8000
#tra_num: 2048
# tra_num: 4096
# tra_num: 6144


# model architectures to train
algorithms:
    - UnrollingModel

# # hyper params for each model
hyperParams:
        UnrollingModel:
            num_blocks:
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
adamParams:
    lr: 0.001
    weight_decay: 0


trainParams:
    num_epochs: 200
    batch_size: 256

lossParams:
        alpha: 0