# Experiment configuration files

# experiment name (determines output folder)
exp_name: unrolling_GNN_WDN
# data folder
data_folder: ./data

# seeds for reproducibility
seeds:
    np: 4320
    torch: 3407

# networks to use
networks: ['temp5', 'FOS']

# number of training samples to use (if < than total)
#tra_num: 8000
tra_num: 8000
# tra_num: 4096
# tra_num: 6144


# model architectures to train
algorithms:
    - MLP
    - GNN
    - Unrolling
    - ModelBased

# # hyper params for each model
hyperParams:
    MLP:
        hid_channels:
            - 16
            - 32
            - 64
        num_layers:
            - 2
            - 4
            - 6
    GNN:
        K:
            - 2
            - 3
            - 4
        hidden_dim:
            - 16
            - 32
        n_gnn_layers:
            - 4
            - 5
            - 6
            - 7
    Unrolling:
        num_blocks:
            - 4
            - 5
            - 6
            - 7
        K:
            - 2
            - 3
            - 4
            - 5
    ModelBased:
        num_blocks:
            - 4
            - 5
            - 6
            - 7
        K:
            - 2
            - 3
            - 4
            - 5
adamParams:
    lr: 1
    weight_decay: 0


trainParams:
    num_epochs: 500
    batch_size: 256

lossParams:
        alpha: 0