# Experiment configuration files

# experiment name (determines output folder)
exp_name: unrolling_WDN
# data folder
data_folder: ../data_generation/datasets

# seeds for reproducibility
seeds:
    np: 4320
    torch: 3407

# networks to use
networks: ['FOS_pump_sched']


# number of training samples to use (if < than total)
tra_num: 1000

# model architectures to train
algorithms:
#    - Dummy
#    - MLPDemandsOnly
    - MLPStatic
#    - LSTM
#    - BaselineUnrolling
#    - UnrollingModel

# hyper params for each model
hyperParams:
        Dummy:
            something:
                - 1
        MLPDemandsOnly:
            hid_channels:
                - 128
            num_layers:
                - 4
        MLPStatic:
            hid_channels:
                - 128
            num_layers:
                - 2
        LSTM:
            hid_channels:
#                - 128
                - 32
            num_layers:
                - 1
#                - 2
#                - 4
        BaselineUnrolling:
            num_blocks:
                - 1
#                - 2
#                - 4
        UnrollingModel:
            num_blocks:
                - 1
#                - 2

adamParams:
    lr: 0.0001
    weight_decay: 0.001


trainParams:
    num_epochs: 500
    batch_size: 32

lossParams:
        alpha: 0

earlyStopping:
    patience: 20
    divisor: 2
    epoch_frequency: 20