# Experiment configuration files

# experiment name (determines output folder)
exp_name: unrolling_GNN_WDN
# data folder
data_folder: ./data

# seeds for reproducibility
seeds:
    np: 4320
    torch: 3407

# networks to use
networks: ['FOS','MOD','PES','BAK','RuralNetwork' ]

# number of training samples to use (if < than total)
tra_num: 8000


# model architectures to train
algorithms:
    - GNN_ChebConv
# # hyper params for each model
hyperParams:
    GNN_ChebConv:
        hid_channels:
            # - 32
            - 64
            - 128
            #- 256
        edge_channels:
            - 32
            - 64
        depth:
            - 1
            - 2
            - 3
        CC_K:
            - 3
            - 6

adamParams:
    lr: 0.001
    weight_decay: 0


trainParams:
    num_epochs: 100
    batch_size: 256

lossParams:
        alpha: 0