# Experiment configuration files

# experiment name (determines output folder)
exp_name: unrolling_WDN
# data folder
data_folder: ../data_generation/datasets

# seeds for reproducibility
seeds:
    np: 4320
    torch: 3407

# networks to use
networks: ['FOS_tank']


# number of training samples to use (if < than total)
tra_num: 5000
# tra_num: 2048
# tra_num: 4096
# tra_num: 6144


# model architectures to train
algorithms:
#    - MLP
    - LSTM
    - BaselineUnrolling
#    - UnrollingModel

# hyper params for each model
hyperParams:
        MLP:
            hid_channels:
                - 64
            num_layers:
                - 2
        LSTM:
            hid_channels:
                - 128
                - 32
            num_layers:
                - 1
                - 2
        BaselineUnrolling:
            num_blocks:
                - 1
                - 2
        UnrollingModel:
            num_blocks:
                - 1
                - 2

adamParams:
    lr: 0.001
    weight_decay: 0.0001


trainParams:
    num_epochs: 1000
    batch_size: 64

lossParams:
        alpha: 0