# Experiment configuration files

# experiment name (determines output folder)
exp_name: unrolling_WDN
# data folder
data_folder: ./data

# seeds for reproducibility
seeds:
    np: 4320
    torch: 3407

# networks to use
networks: ['FOS','MOD','PES','BAK','RuralNetwork' ]

# number of training samples to use (if < than total)
tra_num: 8000
#tra_num: 2048
# tra_num: 4096
# tra_num: 6144


# model architectures to train
algorithms:
    - Unrolling_no_A
    - Unrolling_no_A_no_system_embed
    - Unrolling_no_A_no_system_no_q_embedd
    - Unrolling_no_A_no_D_no_system_embed
    - Unrolling_no_A_no_D_no_q_embedd
    - Unrolling_no_D
    - Unrolling_no_D_no_system_embedd
    - Unrolling_no_D_no_q_embedd
    - Unrolling_no_D_no_system_no_q_embedds
    - Unrolling_no_A_no_D
    - Unrolling_no_system_embeddings
    - Unrolling_no_q_embedding
    - Unrolling_no_system_no_q_embedds
    - BaselineUnrolling

# # hyper params for each model
hyperParams:
        Unrolling_no_A:
            num_blocks:
                - 3
                - 6
                - 7
        Unrolling_no_A_no_system_embed:
            num_blocks:
                - 3
                - 6
                - 7
        Unrolling_no_A_no_system_no_q_embedd:
            num_blocks:
                - 3
                - 6
                - 7
        Unrolling_no_A_no_D_no_system_embed:
            num_blocks:
                - 3
                - 6
                - 7
        Unrolling_no_A_no_D_no_q_embedd:
            num_blocks:
                - 3
                - 6
                - 7
        Unrolling_no_D:
            num_blocks:
                - 3
                - 6
                - 7
        Unrolling_no_D_no_system_embedd:
            num_blocks:
                - 3
                - 6
                - 7
        Unrolling_no_D_no_system_no_q_embedds:
            num_blocks:
                - 3
                - 6
                - 7
        Unrolling_no_D_no_q_embedd:
            num_blocks:
                - 3
                - 6
                - 7
        Unrolling_no_A_no_D:
            num_blocks:
                - 3
                - 6
                - 7
        Unrolling_no_system_embeddings:
            num_blocks:
                - 3
                - 6
                - 7
        Unrolling_no_system_no_q_embedds:
            num_blocks:
                - 3
                - 6
                - 7
        Unrolling_no_q_embedding:
            num_blocks:
                - 3
                - 6
                - 7
        BaselineUnrolling:
            num_blocks:
                - 3
                - 6
                - 7
adamParams:
    lr: 0.001
    weight_decay: 0


trainParams:
    num_epochs: 100
    batch_size: 256

lossParams:
        alpha: 0