# Experiment configuration files

# experiment name (determines output folder)
exp_name: unrolling_WDN
# data folder
data_folder: ../data_generation/datasets

# seeds for reproducibility
seeds:
    np: 4320
    torch: 3407

# networks to use
network: ['FOS_tank']


# number of training samples to use (if < than total)
tra_num: 1000

# model architectures to train
algorithms:
#    - Dummy
    - MLPDynamicOnly
#    - MLPStatic
#    - BaselineUnrolling
#    - UnrollingModelQ
#    - UnrollingModel
#     - UnrollingModelSimple

# hyper params for each model
hyperParams:
        Dummy:
            something:
                - 1
        MLPDynamicOnly:
            hid_channels:
                - 128
            num_layers:
                - 2
        MLPStatic:
            hid_channels:
                - 128
            num_layers:
                - 2
        BaselineUnrolling:
            num_layers:
#                - 1
                - 2
#                - 3
#                - 4
        UnrollingModelSimple:
            num_layers:
#                - 1
                - 2
        UnrollingModel:
            num_layers:
#                - 1
                - 2
#                - 3
#                - 4
        UnrollingModelQ:
            num_layers:
#                - 1
                - 2
#                - 3
#                - 4
adamParams:
    lr: 0.01
    weight_decay: 0.0001


trainParams:
    num_epochs: 500
    batch_size: 128


#lossParams:
#        alpha: 0

earlyStopping:
    patience: 20
    divisor: 2
    epoch_frequency: 20