wandb_version: 1

algorithm:
  value: MLPDemandsOnly
alpha:
  value: 0
batch_size:
  value: 256
divisor:
  value: 2
epoch_frequency:
  value: 50
hid_channels:
  value: 128
learning_rate:
  value: 0.001
num_epochs:
  value: 2000
num_layers:
  value: 4
patience:
  value: 10
weight_decay:
  value: 0.0001
